### ISSUE TITLE
German page does not display video

### ISSUE THREAD

**Issue by peterablehmann** [chaostreff-flensburg/hacks-on-the-harbour-web#18]
When accessing https://hoth.info/de/ the vidio that is right above the program section in the neglish version does not show.

**Comment by peterablehmann** [comment]
Tried the same thing today, but there the bug is reversed. German has the video and English does not.

**Comment by Pizt0lmnk** [comment]
Thanks for catching this, seems like the video is never displayed when initially loading the page. Only switching the language seems to fix this issue at the moment.
The video player is an external plugin which isn't well maintained at the moment. @scammo is there an alternative video player in vuepress?

**Comment by scammo** [comment]
@Pizt0lmnk i tried but could never get to work properly... if anyone knows more about vuepress, I would be glad to help. Longterm plan is to change the static site generator to lume.land (with deno). But we didn't had time so far...
