### ISSUE TITLE
Content not up2date on website

### ISSUE THREAD

**Issue by thies23** [chaostreff-flensburg/hacks-on-the-harbour-web#6]
In Commit 300b21c0e3f57e78b94f1141e4bf79af6fe62f6d @scammo removed the DIY Cloud with Raspberry Pi talk.
This is visible on the German version of the page ( https://www.hoth.info/de/ ) but not on the English version ( https://www.hoth.info/en/ )

**Comment by scammo** [comment]
Markdown is weird! Fixed on [0759410](https://github.com/chaostreff-flensburg/hacks-on-the-harbour-web/commit/07594102e6a2f9b5afc005265630795d2bf2e684) Please Reload.
